export const recentlyAddedAnimeInfos = [{
  id: 'q',
  hoverID: 'asdf',
  name: 'BLADE OF THE IMMORTAL',
  image: 'css/animePosters/BOI_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E6 IN 2 DAYS',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'SHIROBAKO',
  image: 'css/animePosters/SHB_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 23 DAYS',
  opacity: 1,
},
{
  id: 'qwe',
  hoverID: 'asdf',
  name: `KINO'S JOURNEY`,
  image: 'css/animePosters/KJ_Master_300x169.jpg',
  newEpTimes: '&#128344; E6 IN 2 DAYS',
  opacity: 1,
},
{
  id: 'qwer',
  hoverID: 'asdf',
  name: 'THE DEMON SWORD MASTER OF EXCLAIBUR ACADEMY',
  image: 'css/animePosters/DEA_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E11 IN 4 DAYS',
  opacity: 1,
},
{
  id: 'qwert',
  hoverID: 'asdf',
  name: 'TO LOVERU DARKNESS 2',
  image: 'css/animePosters/TLD_02_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 4 DAYS',
  opacity: 1,
},
{
  id: 'qwerty',
  hoverID: 'asdfg',
  name: 'HIMOUTO! UMARU-CHAN',
  image: 'css/animePosters/HUC_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 23 DAYS',
  opacity: 0,
},
{
  id: 'qwertyu',
  hoverID: 'asdfg',
  name: 'KIDS ON THE SLOPE',
  image: 'css/animePosters/KOS_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 23 DAYS',
  opacity: 0,
},
{
  id: 'qwertyui',
  hoverID: 'asdfg',
  name: 'MY LOVE STORY!!',
  image: 'css/animePosters/MLS_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 4 DAYS',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'LOVE, CHUNIBYO & OTHER DELUSIONS! HEART THROB-OVA',
  image: 'css/animePosters/CDK_02_OVA_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 3 DAYS',
  opacity: 0,
},
{
  id: 'qwertyuiop',
  hoverID: 'asdfg',
  name: 'BEYOND THE BOUNDARY-OVA',
  image: 'css/animePosters/BTB_OVA_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E1 IN 2 DAYS',
  opacity: 0,
}]


export const SimulcastAnimeInfos = [{
  id: 'q',
  hoverID: 'asdf',
  name: 'THE VEXATIONS OF A SHUT-IN VAMPIRE PRINCESS',
  image: 'css/SimulcastPosters/VVP_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'RAGNA CRIMSON',
  image: 'css/SimulcastPosters/RCR_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'DARK GATHERING',
  image: 'css/SimulcastPosters/DKG_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TOMORROW',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'THE DEMON SWORD MASTER OF EXCLAIBUR ACADEMY',
  image: 'css/SimulcastPosters/DEA_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E11 IN 2 DAYS',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'HELCK',
  image: 'css/SimulcastPosters/HLK_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; E23 IN 3 DAYS',
  opacity: 1,
},
{
  id: 'qwerty',
  hoverID: 'asdfg',
  name: 'THE EMINENCE IN SHADOW',
  image: 'css/SimulcastPosters/EIS_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'CARDFIGHT!! VANGAURD',
  image: 'css/SimulcastPosters/VWD_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'SPY CLASSROOM',
  image: 'css/SimulcastPosters/SCL_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'THE MOST HERETICAL LAST BOSS QUEEN',
  image: 'css/SimulcastPosters/HLB_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'THE DREAMING BOY IS A REALIST',
  image: 'css/SimulcastPosters/DBR_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
}]


export const exclusivesAnimeInfos = [{
  id: 'q',
  hoverID: 'asdf',
  name: 'DARK GATHERING',
  image: 'css/SimulcastPosters/DKG_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'LOVE, CHUNIBYO & OTHER DELUSIONS!-OVA',
  image: 'css/ExclusivePosters/CDK_01_OVA_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'LOVE, CHUNIBYO & OTHER DELUSIONS! HEART THROB-OVA',
  image: 'css/ExclusivePosters/CDK_02_OVA_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'LOVE FLOPS',
  image: 'css/ExclusivePosters/LFP_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'PHANTOM OF THE IDOL',
  image: 'css/ExclusivePosters/PHI_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; TODAY',
  opacity: 1,
},
{
  id: 'qwerty',
  hoverID: 'asdfg',
  name: 'THE DREAMING BOY IS A REALIST',
  image: 'css/ExclusivePosters/DBR_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'GUNBUSTER THE MOVIE',
  image: 'css/ExclusivePosters/GNB_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'THE DEMON SWORD MASTER OF EXCLAIBUR ACADEMY',
  image: 'css/SimulcastPosters/DEA_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'THE VEXATIONS OF A SHUT-IN VAMPIRE PRINCESS',
  image: 'css/SimulcastPosters/VVP_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'RAGNA CRIMSON',
  image: 'css/SimulcastPosters/RCR_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
}]


export const IntroToHidiveAnimeInfos = [{
  id: 'q',
  hoverID: 'asdf',
  name: 'REAL GIRL',
  image: 'css/IntroToHidivePosters/real-girl_RLG_01_MASTER_300x169_01.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'LEGEND OF THE GALACTIC HEROES',
  image: 'css/IntroToHidivePosters/LegendGalacticHeroes_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'BLOOM INTO YOU',
  image: 'css/IntroToHidivePosters/BIB_01_MASTER_300x169_01.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'GATE',
  image: 'css/IntroToHidivePosters/GTE_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'IS IT WRONG TO PICK UP GIRLS IN A DUNGEON',
  image: 'css/IntroToHidivePosters/WPG_OVA_MASTER_300x169_v02.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qwerty',
  hoverID: 'asdfg',
  name: 'MADE IN ABYSS',
  image: 'css/IntroToHidivePosters/made-in-abyss_MIA_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'FOOD WARS!',
  image: 'css/IntroToHidivePosters/FDW_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'MY GIRLFRIEND IS A SHOBITCH',
  image: 'css/IntroToHidivePosters/FVB_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: `MONTHLY GILRS' NOZAKI-KUN`,
  image: 'css/IntroToHidivePosters/MGN_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'DOMESTIC GIRLFRIEND',
  image: 'css/IntroToHidivePosters/DGF_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
}]


export const TrendingNowAnimeInfos = [{
  id: 'q',
  hoverID: 'asdf',
  name: 'THE EMINENCE IN SHADOW',
  image: 'css/SimulcastPosters/EIS_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'THE SEVEN HEAVENLY VIRTUES',
  image: 'css/TrendingnowPosters/SHV_01_MASTER_300x169_01.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'RE:CYCLE OF THE PENGUINDRUM MOVIE',
  image: 'css/TrendingnowPosters/PGD_MOVIE2_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'HELCK',
  image: 'css/SimulcastPosters/HLK_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qw',
  hoverID: 'asdf',
  name: 'THE DEMON SWORD MASTER OF EXCLAIBUR ACADEMY',
  image: 'css/SimulcastPosters/DEA_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 1,
},
{
  id: 'qwerty',
  hoverID: 'asdfg',
  name: 'MANAGEMENT OF A NOVICE ALCHEMIST',
  image: 'css/TrendingnowPosters/MNA_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'ENDO AND KOBAYASHI, LIVE! THE LATEST ON TSUNDERE',
  image: 'css/TrendingnowPosters/EKL_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'LEVEL 1 DEMON LORD & ONE ROOM HERO',
  image: 'css/TrendingnowPosters/ORH_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'GATE',
  image: 'css/IntroToHidivePosters/GTE_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
},
{
  id: 'qwertyuio',
  hoverID: 'asdfg',
  name: 'PHANTOM OF THE IDOL',
  image: 'css/ExclusivePosters/PHI_01_MASTER_300x169.jpg',
  newEpTimes: '&#128344; FINISHED',
  opacity: 0,
}]